.TH "QABC" "1" 
.SH "NAME" 
qabc \(em minimal GUI for ABC music notation 
.SH "SYNOPSIS" 
.PP 
\fBqabc\fR [file.abc] ...
.SH "DESCRIPTION" 
.PP 
This manual page documents the \fBqabc\fR program. 
.PP 
\fBqabc\fR is a minimal graphical program that allow one to edit musical scores 
in the ABC format. 
 
.PP 
\fBqabc\fR uses third-party software to view the generated score and to play audio.
For now, qabc uses by default: abc2midi to generate MIDI, fluidsynth to play MIDI,
and abcm2ps to generate Postscript, plus evince to view the generated score.
 
.\" created by instant / docbook-to-man 
