abcparse: libabcparse.a main.o abcsmf.o
	$(CC) -g main.o abcsmf.o  -L. -labcparse -o $@ $(shell pkg-config --libs smf)

%.o: %.c
	$(CC) -g -c $< $(shell pkg-config --cflags smf)

libabcparse.a: parser.o abc.o abcparse.o
	$(RM) libabcparse.a
	ar r libabcparse.a parser.o abc.o abcparse.o
	ar -s libabcparse.a

parser.c: parser.peg
	packcc $<

clean:
	$(RM) *.o

distclean: clean
	$(RM) abcparse libabcparse.a
